import ParallaxBg from '@/components/paralaxhero/ParallaxBg'

export default function Page() {
  return (
    <div>
      <ParallaxBg/>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
      <div>amir</div>
    </div>
  )
}